### ISSUE TITLE
Treat the single of old posts, the ones with no language

### ISSUE THREAD

**Issue by chandonn-zz** [brenoalvs/monk#109] opened 2016-12-23 12:11 UTC
![screenshot from 2016-12-23 10 07 03](https://cloud.githubusercontent.com/assets/22301205/21453602/e89ec74e-c8f7-11e6-9006-895773b2b5ce.png)

A parameter must be passed for the Language Switcher inside old posts, in the single

**Comment by brenoalvs** [comment] 2017-01-09 23:57
Duplicate of #106

**Closed as completed by brenoalvs** 2017-01-09 23:57 UTC
Labels: duplicate
